import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import cookie from "js-cookie";
import { useRouter } from "next/router";
import styles from "@/styles/Home.module.css";
import Cards from "@/components/cards/Cards";
import PageTemplate from "@/components/pageTemplate/PageTemplate";

export default function Home() {
	const [locations, setLocations] = useState<Array<any> | null>(null);
	const router = useRouter();

	useEffect(() => {
		const getLocations = async () => {
			try {
				const headers = {
					authorization: cookie.get("jwt_token"),
				};
				if (!headers) {
					router.push("/login");
				}
				const response = await axios.get(
					`${process.env.SERVER_URL}/locations`,
					{
						headers,
					}
				);
				console.log(response);

				setLocations(response.data.locations);
			} catch (error) {
				console.error("Error fetching locations:", error);
			}
		};

		getLocations();
	}, []);

	return (
		<PageTemplate>
			<Head>
				<title>Top Lithuania`s Locations</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Cards locations={locations} />
			</main>
		</PageTemplate>
	);
}
